### ISSUE TITLE
Failed Installation of sale_price_purchase

### ISSUE THREAD

**Issue by mfaheemkhan6** [nicolasramos-es/odoo#1]
Traceback (most recent call last):
  File "/opt/Software/Software/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/Software/Software/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/Software/Software/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/Software/Software/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/Software/Software/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/Software/Software/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/Software/Software/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/Software/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/Software/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/Software/Software/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/Software/Software/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/Software/Software/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/Software/Software/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/Software/Software/modules/registry.py", line 78, in new
    Software.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/Software/Software/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/Software/Software/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/Software/Software/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/Software/Software/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/Software/Software/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/Software/Software/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/Software/Software/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/Software/Software/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/Software/Software/addons/base/ir/ir_model.py", line 1191, in _update
    record = record.create(values)
  File "/opt/Software/Software/addons/base/ir/ir_ui_view.py", line 360, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/Software/Software/models.py", line 3823, in create
    self._fields[key].determine_inverse(record)
  File "/opt/Software/Software/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/Software/Software/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/opt/Software/Software/addons/base/ir/ir_ui_view.py", line 378, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/Software/Software/models.py", line 3555, in write
    self._write(old_vals)
  File "/opt/Software/Software/models.py", line 3701, in _write
    self._validate_fields(vals)
  File "/opt/Software/Software/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Field `origin` does not exist

Error context:
View `sale_price_purchase.order.line.form`
[view_id: 768, xml_id: n/a, model: purchase.order.line, parent_id: 692]
None" while parsing /opt/Software/custom-addons/difusionvisual/sale_price_purchase/views/sale_price_purchase.xml:4, near
<record model="ir.ui.view" id="sale_price_purchase_order_line_form">
        <field name="name">sale_price_purchase.order.line.form</field>
        <field name="model">purchase.order.line</field>
        <field name="inherit_id" ref="purchase.purchase_order_form"/>
        <field name="arch" type="xml">
            <field name="price_unit" position="after">
                <field name="sale_price"/>
            </field>
        </field>
    </record>

**Comment by Bioriginal** [comment]
Same problem here, did you find a solution  for the missing field ?
